name: weather_app_sample
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.3"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.4
  riverpod: ^1.0.3
  freezed_annotation: ^2.0.3
  fluttertoast:
    git:
      url: https://github.com/yuchan2215/FlutterToast.git
      ref: master
  flutter_secure_storage: ^5.0.2
  async: ^2.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  mockito: ^5.2.0
  flutter_driver:
    sdk: flutter
  test: any


flutter:
  uses-material-design: true
