name: flutter integration test

on: workflow_dispatch


jobs:
  integration_test:
    strategy:
      matrix:
        device:
          - "iPhone 12 Pro"
          - "iPhone 8"
      fail-fast: false
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: "list"
        run: |
          xcrun xctrace list devices
      - name: "start simulator"
        timeout-minutes: 10
        run: |
          FIND="iPhone 11 Pro"
          FIND_REGEX=".*\(([0-9A-Z-]+)\)$"
          UDID=$(
            xcrun xctrace list devices | grep "${{ matrix.device }} Simulator" |
            grep -v "Apple Watch" |
            sed -r "s/$FIND_REGEX/\1/"
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.3'
      - run: "flutter drive --target=test_driver/app.dart"