name: flutter integration test

on: workflow_dispatch


jobs:
  integration_test:
    strategy:
      matrix:
        device:
          - "iPhone 8"
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: "start simulator"
        timeout-minutes: 10
        run: |
          sh ./.github/workflows/simulator_start.sh "${{ matrix.device }}"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.3'
      - name: "test"
        run: |
          sh ./.github/workflows/drive_test.sh "${{ matrix.device }}"
      - name: "shutdown simulator"
        run: |
          sh ./.github/workflows/simulator_shutdown.sh "${{ matrix.device }}"

  integration_test_android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 23 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
          cache: 'gradle'
      - uses: gradle/gradle-build-action@v2
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.3'
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            flutter drive --driver=test_driver/integration_test.dart --target=test_driver/hoge_test.dart -d "emulator-5554"

